### ISSUE TITLE
prc/graph can't display fonts

### ISSUE THREAD

**Issue by robert-johansson** [jasongilman/proto-repl-charts#10]
I'm playing around with the graph examples from proto-repl-charts.

However, the vis.js-based graphs seems not to work on my setup.

The following code
`(prc/graph
 "A Graph from a map"
 {:nodes [:a :b :c :d :e :f :g]
  :edges [[:d :b] [:b :c] [:d :c] [:e :f] [:f :g]
          [:d :a] [:f :c]]})`

leads to a graph with only blocks instead of any text displayed. Similar behavior with the loom graphs.

https://goo.gl/photos/zxPPBzMYQqtJrQ667

Any idea on how to resolve this is very welcome!

Thanks,
Robert

**Comment by jasongilman** [comment]
It looks like there's something wrong with the background color style of text code. Can you use the developer tools and select the canvas to show the styles and capture an image like the following one? It may show if there's an errant style applied

<img width="1434" alt="graphs_md_ __users_jason_work_github_workspace_proto-repl-charts" src="https://cloud.githubusercontent.com/assets/192983/19017690/7fab3ce4-8811-11e6-9f4c-9febfbf308bf.png">

**Comment by robert-johansson** [comment]
Hi Jason - thanks. Here's a captured image: 

<img src="https://lh3.googleusercontent.com/jEoHrsSwaLwTaP_S2LZlYGSwQmrIOhzufAPq_RPw33DnG9mxNo9Q5CuwFlHmA9_IJ9KCV3MDGuelRhH17GzO6qepZX836OJNYPUmT2e-vfJ0vI_PGqY5nTgo4LZtBeWGJDjArXYqlCHdaEcFh33JvNDSBesV4aB1kfCm41ncm3zkaQ4KGeLybsf23WTxea6CzzF02maYOF5NUBZk2Or8oL4K8kPmduK9Y_btpqobQ1Pr_UtoGncyDsZ67_gs2Zy1A-VPfcBGfzvCtb166sD9pmaKv1gBTq1kS_zo2NR3euWpK41m0QRoSGt-F9wad7i-d__sGwuUoRoQto9k4nNdBHYIv9YezThG-gpRy6mPohl_wrb6DMg83USAfjdQZa9KTyaSeIi1GEfJ8lWaCt4Ir213SPpB8PQqHi2cO4g8c54Z3Yf90oOa3O6jN5Ak5lRGvILnpOTd_0wEKrlYx-aqA7GlgWJyvL09CYYM2z1II_nmPtFYuDFwt7fktqMxCX0v86-mpxNtLpYIF_acsIMLs6mFM6Hy98_p1yV_a8sd0WyREnT1ZqilyGw38ggjImyo2UBdzIDKO_zSxNC7_Mr6XqHQWFj8Nua1kO4J-ICh_PrzefkEOg=w2304-h1440-no" />

**Comment by robert-johansson** [comment]
Image was not displayed correctly:
<img width="1440" alt="skarmavbild 2016-10-02 kl 07 23 54" src="https://cloud.githubusercontent.com/assets/8457281/19019521/97625ec4-888b-11e6-86ff-87c71892e85e.png">

**Comment by mojoaxel** [comment]
vis.js should be updated to the latest version. But I I'm not sure that will fix the problem.

**Comment by robert-johansson** [comment]
@mojoaxel Thanks for the suggestion. If I want to try that out, how do I update vis.js to the latest version?

**Comment by jasongilman** [comment]
@robert-johansson  I was able to change the background color of the nodes try running this:

```
(proto-repl-charts.graph/graph
  "A Graph from a map"
  {:nodes [:a :b :c :d :e :f :g]
   :edges [[:d :b] [:b :c] [:d :c] [:e :f] [:f :g]
           [:d :a] [:f :c]]}
  {:nodes {:font {:background "yellow"}}})
```

You can also try specifying the background color as "none" and not see those black rectangles.

**Comment by jasongilman** [comment]
According to the vis.js documentation the background color should be "none" by default. http://visjs.org/docs/network/nodes.html# When I tried changing it to something like #343434 I got the same black squares you saw.

**Comment by robert-johansson** [comment]
@jasongilman Weird - it still doesn't work. I have a gut feeling that it is related to something on my local setup of Atom. I haven't changed very much though beyond adding themes.

![skarmavbild 2016-10-05 kl 09 18 46](https://cloud.githubusercontent.com/assets/8457281/19104480/0202ce28-8add-11e6-9135-05c369d901cb.png)

**Comment by mojoaxel** [comment]
@robert-johansson I dont have time to look into this at the moment but I would recommend fiddling with the `font`settings of the nodes (here the default):

``` js
nodes:{
  font: {
      color: '#343434',
      size: 14, // px
      face: 'arial',
      background: 'none',
      strokeWidth: 0, // px
      strokeColor: '#ffffff',
      align: 'center'
    }
}
```

Try to change the face or the background to `transparent` or something...I Hope this helps!

**Comment by robert-johansson** [comment]
@jasongilman @mojoaxel Thanks a lot for your suggestions. I have installed Atom+proto-repl on a fresh install of macOS, and now the graphs works great! Whatever caused it remains a myster :)
