### ISSUE TITLE
Can't get this to work in self hosted REPL

### ISSUE THREAD

**Issue by yihongang** [jasongilman/proto-repl-charts#14]
Following the README  just gets me

    TypeError: Cannot read property 'line_chart' of undefined

Also followed `Option 2. Opinionated, Complete, Best Way to Setup Atom for Clojure Development with Proto REPL` for setting up

**Comment by jasongilman** [comment]
I think that I haven't updated the version of Proto REPL charts in the self hosted REPL. That might be the problem depending on what code you're executing. You can work around it by using the normal REPL.

**Comment by yihongang** [comment]
OK thanks!
