### ISSUE TITLE
After closing a tab with a chart I can not reopen that chart

### ISSUE THREAD

**Issue by jasongilman** [jasongilman/proto-repl-charts#3]
Nothing happens there is no error. Choosing a different name allows it to be reopened.

**Comment by ghost** [comment]
Same issue here with following code:

``` clojure
(defn f [x] (* x x))
(prc/line-chart "My F" {"f" (map f (range 0.0 0.6 0.2))})
```

This code, however, reopens its chart:

``` clojure
(prc/line-chart "MyF" {"f" (map f (range 0.0 0.6 0.2))})
```

The issue appears to be the spaces in the chart name. When I name it e.g. "M y F", I again get a chart that cannot be reopened.

**Comment by jasongilman** [comment]
It was related to the spaces in the name. Good catch.
